def make_house_info():
    house_info = {1: {'id':'19B2f6SRrrqBaB58tH7wvzX6qBKwvAeBy',
                    'Dishwasher': 'Appliance6', 
                    'Washing Machine': 'Appliance5',
                    'Tumble Dryer': 'Appliance4',
                    'Fridge': 'Appliance1',
                    'Electric Heater': 'Appliance9',
                    'Freezer': 'Appliance2'},         
                2: {'id': '1QnnmIsepB6ThZgJQuYy_JjZ961-fdzwp',
                    'Dishwasher': 'Appliance3', 
                    'Washing Machine': 'Appliance2',
                    'Fridge': 'Appliance1',
                    'Microwave': 'Appliance5',
                    'Kettle': 'Appliance8',
                    'Toaster': 'Appliance6'}, 
                3: {'id': '1EVouoLWiCINUgokLZ_g2J0xTmj77nwgt',
                    'Dishwasher': 'Appliance5', 
                    'Washing Machine': 'Appliance6',
                    'Tumble Dryer': 'Appliance4',
                    'Fridge': 'Appliance2',
                    'Microwave': 'Appliance8',
                    'Kettle': 'Appliance9',
                    'Freezer': 'Appliance3',
                    'Toaster': 'Appliance1'}, 
                4: {'id': '1k2Yn70BEtLNgDErlZFNAP4fNvS5AjhC_',
                    'Washing Machine': 'Appliance4',
                    'Fridge': 'Appliance1',
                    'Microwave': 'Appliance8',
                    'Kettle': 'Appliance9',
                    'Freezer': 'Appliance2'}, 
                5: {'id': '1pnPIIyIM0Fgb2Kj0AAqSvAWJRsy9p8jH',
                    'Dishwasher': 'Appliance4', 
                    'Washing Machine': 'Appliance3',
                    'Tumble Dryer': 'Appliance2',
                    'Fridge': 'Appliance1',
                    'Microwave': 'Appliance7',
                    'Kettle': 'Appliance8',
                    'Toaster': 'Appliance9'},
                6: {'id':'1UM9aBDrLcyTh8pWVaJcfGea9uL73AOSJ',
                    'Dishwasher': 'Appliance3', 
                    'Washing Machine': 'Appliance2',
                    'Microwave': 'Appliance6',
                    'Kettle': 'Appliance7',
                    'Freezer': 'Appliance1',
                    'Toaster': 'Appliance8'}, 
                7: {'id':'1zxf1uR_xp595kehbEGiIZWEBHwPUa41y',
                    'Dishwasher': 'Appliance6', 
                    'Washing Machine': 'Appliance5',
                    'Tumble Dryer': 'Appliance4',
                    'Fridge': 'Appliance1',
                    'Kettle': 'Appliance9',
                    'Freezer': 'Appliance3',
                    'Toaster': 'Appliance8'}, 
                8: {'id': '1md5pOhtWyf5qy27buj4iIZ1WogD7_rJk',
                    'Washing Machine': 'Appliance4',
                    'Tumble Dryer': 'Appliance3',
                    'Fridge': 'Appliance1',
                    'Microwave': 'Appliance8',
                    'Kettle': 'Appliance9',
                    'Freezer': 'Appliance2',
                    'Toaster': 'Appliance5'}, 
                9: {'id': '1bx0fl_lJFoofLqoogAE4I7YKRnjKzHLa',
                    'Dishwasher': 'Appliance4', 
                    'Washing Machine': 'Appliance3',
                    'Tumble Dryer': 'Appliance2',
                    'Fridge': 'Appliance1',
                    'Microwave': 'Appliance6',
                    'Kettle': 'Appliance7',
                    'Electric Heater': 'Appliance9'}, 
                10: {'id': '1gVNOO87i2ohN59ZEdM53VPnoARAfJ28A',
                    'Dishwasher': 'Appliance6', 
                    'Washing Machine': 'Appliance5',
                    'Fridge': 'Appliance4',
                    'Microwave': 'Appliance8',
                    'Freezer': 'Appliance2'}, 
                11: {'id': '1ujUjRoH1gOJnnCFw6qKYbXXHzRoPSIHH',
                    'Dishwasher': 'Appliance4', 
                    'Washing Machine': 'Appliance3',
                    'Fridge': 'Appliance1',
                    'Microwave': 'Appliance6',
                    'Kettle': 'Appliance7'}, 
                12: {'id': '1CW29JzoWTvYZ8IvJwhHeBC0OMCqrkfaf',
                    'Fridge': 'Appliance1',
                    'Microwave': 'Appliance3',
                    'Kettle': 'Appliance4',
                    'Toaster': 'Appliance5'}, 
                13: {'id': '1rIpoZEM5Iyj_yTOkJy8tLyqsL8Y08yjK',
                    'Dishwasher': 'Appliance4', 
                    'Washing Machine': 'Appliance3',
                    'Tumble Dryer': 'Appliance5',
                    'Microwave': 'Appliance8',
                    'Kettle': 'Appliance9'}, 
                15: {'id': '1TWwwjkrj_m61j7vTxWBDJ389VXEe4YLB',
                    'Dishwasher': 'Appliance4', 
                    'Washing Machine': 'Appliance3',
                    'Tumble Dryer': 'Appliance2',
                    'Fridge': 'Appliance1',
                    'Microwave': 'Appliance7',
                    'Kettle': 'Appliance8',
                    'Toaster': 'Appliance9'}, 
                16: {'id': '1l0l7AVbAEpnvahaoWKuS4VCAJluAQT8G',
                    'Dishwasher': 'Appliance6', 
                    'Washing Machine': 'Appliance5',
                    'Fridge': 'Appliance1',
                    'Electric Heater': 'Appliance4'}, 
                17: {'id': '1-2fxEU7XABgK-NXwGarkWvUkwaM2ziww',
                    'Washing Machine': 'Appliance4',
                    'Tumble Dryer': 'Appliance3',
                    'Fridge': 'Appliance2',
                    'Microwave': 'Appliance7',
                    'Kettle': 'Appliance8',
                    'Freezer': 'Appliance1'}, 
                18: {'id': '1EtILgzVVk-RTHeSRDxIP6e6VesFjQ5pE',
                    'Dishwasher': 'Appliance6', 
                    'Washing Machine': 'Appliance5',
                    'Fridge': 'Appliance3',
                    'Microwave': 'Applianc9',
                    'Freezer': 'Appliance2'}, 
                19: {'id': '12_8tqPJzVKORW7WHRVV-ZF5S4W3Wpaem',
                    'Washing Machine': 'Appliance2',
                    'Fridge': 'Appliance1',
                    'Microwave': 'Appliance4',
                    'Kettle': 'Appliance5',
                    'Toaster':'Appliance6'}, 
                20: {'id': '1mWiSaSaFS3wJIAXtHJGu7RfVw_alDwQf',
                    'Dishwasher': 'Appliance5', 
                    'Washing Machine': 'Appliance4',
                    'Tumble Dryer': 'Appliance3',
                    'Fridge': 'Appliance1',
                    'Microwave': 'Appliance8',
                    'Kettle': 'Appliance9',
                    'Freezer': 'Appliance2'}, 
                21: {'id': '1egzpS0Scr18svZ_r05kajA7fKM25H6Qt',
                    'Dishwasher': 'Appliance4', 
                    'Washing Machine': 'Appliance3',
                    'Tumble Dryer': 'Appliance2',
                    'Fridge': 'Appliance1',
                    'Kettle': 'Appliance7'}
                    }
    return house_info

house_info = make_house_info()